### ISSUE TITLE
the package is not installed

### ISSUE THREAD

**Issue by dd-dev** [sinfo/ampersand-pikaday-view#2]
npm i --save ampersand-pikaday-view
npm WARN deprecated ampersand-state@4.9.1: Breaking changes were inadvertantly introduced in ampersand-state@4.9.0-1. Please pin your dependency
 at 4.8.2 or update to ^5.0.0.  See the note in the readme for state.set for more info
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "--save" "ampersand-pika
day-view"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: get-object-path@^0.0.2
npm ERR! Valid install targets:
npm ERR! 0.0.3
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\vedapulse-electron\vedapulse-electron-website\npm-debug.log

**Comment by JGAntunes** [comment]
Hey @dd-dev, sorry for taking so long to reply.

I'm unable to reproduce this, although I'm running it on Linux, and seems to me that the mentioned package exists on the registry - https://npmcdn.com/get-object-path@0.0.2 - Could you confirm that this issue is still happening?
